// Copyright 2023-2024 The Regents of the University of California
// Copyright 2024 Cornell University
// released under BSD 3-Clause License
// author: Kevin Laeufer <laeufer@cornell.edu>

use super::parse::{
    DEFAULT_BAD_STATE_PREFIX, DEFAULT_CONSTRAINT_PREFIX, DEFAULT_INPUT_PREFIX,
    DEFAULT_OUTPUT_PREFIX, DEFAULT_STATE_PREFIX,
};
use crate::expr::*;
use crate::system::{State, TransitionSystem};
use baa::BitVecOps;
use rustc_hash::FxHashMap;
use std::io::Write;

/// The patronus parser assigns default names of the form `_state`, `_state_0`, `_state_1`,
/// ... to symbols that arrive without an explicit name in the source BTOR2. Re-serializing
/// those synthesized names and re-parsing them pollutes the parser's unique-name namespace
/// and forces unwanted `_N` suffixes on unrelated symbols, which breaks round-trips. We
/// filter such names back out on the way to BTOR2 and let the parser regenerate them.
fn is_autogen_name(name: &str) -> bool {
    const PREFIXES: &[&str] = &[
        DEFAULT_STATE_PREFIX,
        DEFAULT_INPUT_PREFIX,
        DEFAULT_OUTPUT_PREFIX,
        DEFAULT_BAD_STATE_PREFIX,
        DEFAULT_CONSTRAINT_PREFIX,
    ];
    for prefix in PREFIXES {
        if name == *prefix {
            return true;
        }
        if let Some(rest) = name.strip_prefix(prefix)
            && let Some(tail) = rest.strip_prefix('_')
            && !tail.is_empty()
            && tail.chars().all(|c| c.is_ascii_digit())
        {
            return true;
        }
    }
    false
}

pub fn serialize(
    ctx: &Context,
    writer: &mut impl Write,
    sys: &TransitionSystem,
) -> std::io::Result<()> {
    Serializer::new(ctx, writer).serialize_sys(sys)
}

const VERSION: Option<&str> = option_env!("CARGO_PKG_VERSION");

pub fn serialize_to_str(ctx: &Context, sys: &TransitionSystem) -> String {
    let mut buf = Vec::new();
    serialize(ctx, &mut buf, sys).expect("Failed to write to string!");
    String::from_utf8(buf).expect("Failed to read string we wrote!")
}

struct Serializer<'a, W: Write> {
    ctx: &'a Context,
    writer: &'a mut W,
    next_id: u64,
    sort_ids: FxHashMap<Type, u64>,
    expr_ids: SparseExprMap<Option<u64>>,
}

impl<'a, W: Write> Serializer<'a, W> {
    fn new(ctx: &'a Context, writer: &'a mut W) -> Self {
        Serializer {
            ctx,
            writer,
            next_id: 1,
            sort_ids: FxHashMap::default(),
            expr_ids: SparseExprMap::default(),
        }
    }

    fn new_id(&mut self) -> u64 {
        let id = self.next_id;
        self.next_id += 1;
        id
    }

    fn sort_id(&mut self, tpe: Type) -> std::io::Result<u64> {
        if let Some(&id) = self.sort_ids.get(&tpe) {
            return Ok(id);
        }
        let id = match tpe {
            Type::BV(w) => {
                let id = self.new_id();
                writeln!(self.writer, "{id} sort bitvec {w}")?;
                id
            }
            Type::Array(ArrayType {
                index_width,
                data_width,
            }) => {
                let ix = self.sort_id(Type::BV(index_width))?;
                let dx = self.sort_id(Type::BV(data_width))?;
                let id = self.new_id();
                writeln!(self.writer, "{id} sort array {ix} {dx}")?;
                id
            }
        };
        self.sort_ids.insert(tpe, id);
        Ok(id)
    }

    fn serialize_sys(&mut self, sys: &TransitionSystem) -> std::io::Result<()> {
        writeln!(
            self.writer,
            "; btor2 description of `{}` generated by patronus {}",
            sys.name,
            VERSION.unwrap_or_default()
        )?;

        // Names that appear on output/bad/constraint lines. A state or input whose
        // symbol already carries such a name must be declared *without* a name on the
        // BTOR2 line: otherwise the second line (the `output` etc.) would be forced to
        // rename via `add_unique_str`, breaking idempotent round-trips. Patronus's
        // `improve_state_names` recovers the symbol name on re-parse.
        let label_names = collect_label_names(self.ctx, sys);

        // Labels (outputs/bads/constraints) directly referencing a state expression, and
        // whose label name differs from the state's symbol name. For each such state we
        // must defer the state's name to a trailing `uext <state> 0 <name>` alias line:
        // otherwise the output line's `sys.names` overwrite + `improve_state_names`
        // would rename the state on re-parse.
        let alias_needed = compute_alias_needed(self.ctx, sys);

        // 1. declare inputs
        for &input in sys.inputs.iter() {
            let tpe = input.get_type(self.ctx);
            let sort = self.sort_id(tpe)?;
            let id = self.new_id();
            let raw = self.ctx[input].get_symbol_name(self.ctx).unwrap_or("");
            let name = decl_name(raw, &label_names);
            writeln!(self.writer, "{id} input {sort}{}", name_suffix(name))?;
            self.expr_ids[input] = Some(id);
        }

        // 2. declare states (decl only; init/next come at the end)
        let mut state_ids: Vec<u64> = Vec::with_capacity(sys.states.len());
        for state in sys.states.iter() {
            let tpe = state.symbol.get_type(self.ctx);
            let sort = self.sort_id(tpe)?;
            let id = self.new_id();
            let raw = self.ctx[state.symbol]
                .get_symbol_name(self.ctx)
                .unwrap_or("");
            let name = if alias_needed.contains(&state.symbol) {
                "" // trailing alias line will reassert the name
            } else {
                decl_name(raw, &label_names)
            };
            writeln!(self.writer, "{id} state {sort}{}", name_suffix(name))?;
            self.expr_ids[state.symbol] = Some(id);
            state_ids.push(id);
        }

        // 3. outputs
        for out in sys.outputs.iter() {
            let body_id = self.emit_expr(out.expr)?;
            let id = self.new_id();
            let name = self.ctx[out.name].clone();
            writeln!(self.writer, "{id} output {body_id}{}", name_suffix(&name))?;
        }

        // 4. constraints
        for (i, &c) in sys.constraints.iter().enumerate() {
            let body_id = self.emit_expr(c)?;
            let id = self.new_id();
            let name = label_name(self.ctx, sys, c, "constraint", i);
            writeln!(self.writer, "{id} constraint {body_id}{}", name_suffix(&name))?;
        }

        // 5. bad states
        for (i, &b) in sys.bad_states.iter().enumerate() {
            let body_id = self.emit_expr(b)?;
            let id = self.new_id();
            let name = label_name(self.ctx, sys, b, "bad", i);
            writeln!(self.writer, "{id} bad {body_id}{}", name_suffix(&name))?;
        }

        // 6. trailing aliases: reassert each affected state's name.
        for (state, &state_id) in sys.states.iter().zip(state_ids.iter()) {
            if !alias_needed.contains(&state.symbol) {
                continue;
            }
            let raw = self.ctx[state.symbol]
                .get_symbol_name(self.ctx)
                .unwrap_or("");
            if raw.is_empty() {
                continue;
            }
            let sort = self.sort_id(state.symbol.get_type(self.ctx))?;
            let id = self.new_id();
            // `uext ... 0` is the idiomatic alias pattern the parser already recognizes;
            // see `improve_state_names`. With the state decl emitted unnamed above,
            // `raw` is guaranteed unique at this point in the parser's namespace.
            writeln!(self.writer, "{id} uext {sort} {state_id} 0 {raw}")?;
        }

        // 7. init / next per state
        for (state, &state_id) in sys.states.iter().zip(state_ids.iter()) {
            let state_sort = self.sort_id(state.symbol.get_type(self.ctx))?;
            if let Some(init) = state.init {
                let init_id = self.emit_state_init(state, init)?;
                let id = self.new_id();
                writeln!(self.writer, "{id} init {state_sort} {state_id} {init_id}")?;
            }
            if let Some(next) = state.next {
                let next_id = self.emit_expr(next)?;
                let id = self.new_id();
                writeln!(self.writer, "{id} next {state_sort} {state_id} {next_id}")?;
            }
        }

        Ok(())
    }

    /// BTOR2 lets you initialize an array state from a bit-vector value directly: the
    /// `init` line carries the array sort but a BV-sort node. The parser re-wraps such
    /// cases into `ArrayConstant`, so on the way out we unwrap the BV and let the init
    /// line handle the rest.
    fn emit_state_init(&mut self, state: &State, init: ExprRef) -> std::io::Result<u64> {
        if state.symbol.get_type(self.ctx).is_array()
            && let Expr::ArrayConstant { e, .. } = self.ctx[init]
        {
            return self.emit_expr(e);
        }
        self.emit_expr(init)
    }

    /// Emit this expression (and all sub-expressions) in post-order. Symbols must already
    /// be registered via `expr_ids` (inputs/states).
    fn emit_expr(&mut self, e: ExprRef) -> std::io::Result<u64> {
        if let Some(id) = self.expr_ids[e] {
            return Ok(id);
        }

        let expr = self.ctx[e].clone();

        if expr.is_symbol() {
            let name = expr.get_symbol_name(self.ctx).unwrap_or("?");
            panic!(
                "encountered unregistered symbol `{name}` while serializing btor2 — \
                 every symbol must be declared as an input or state"
            );
        }

        // emit children first so they have assigned ids
        let mut children: Vec<ExprRef> = Vec::with_capacity(3);
        expr.for_each_child(|c| children.push(*c));
        let child_ids: Vec<u64> = children
            .into_iter()
            .map(|c| self.emit_expr(c))
            .collect::<Result<_, _>>()?;

        let tpe = expr.get_type(self.ctx);
        let sort = self.sort_id(tpe)?;
        let id = self.new_id();

        write_node(self.writer, self.ctx, id, sort, &expr, &child_ids)?;

        self.expr_ids[e] = Some(id);
        Ok(id)
    }
}

fn name_suffix(name: &str) -> String {
    if name.is_empty() {
        String::new()
    } else {
        format!(" {name}")
    }
}

/// Pick the name to emit on a symbol's declaration line. We omit the name in two cases:
/// (1) the symbol carries an autogenerated default prefix (the parser will regenerate it),
/// (2) the name would clash with an output/bad/constraint label (in which case the parser's
/// `improve_state_names` pass will propagate the name back onto the symbol on re-parse).
fn decl_name<'a>(
    raw: &'a str,
    label_names: &rustc_hash::FxHashSet<String>,
) -> &'a str {
    if raw.is_empty() || is_autogen_name(raw) || label_names.contains(raw) {
        ""
    } else {
        raw
    }
}

/// Returns the set of state symbols that need a trailing `uext 0` alias line to preserve
/// their name across a round-trip. A state is flagged when at least one direct reference
/// from an output/bad/constraint uses a different name than the state's current symbol
/// name — the parser's `improve_state_names` pass would otherwise override the state's
/// name with that label's name on re-parse.
fn compute_alias_needed(
    ctx: &Context,
    sys: &TransitionSystem,
) -> rustc_hash::FxHashSet<ExprRef> {
    let mut state_symbols = rustc_hash::FxHashSet::default();
    for state in sys.states.iter() {
        state_symbols.insert(state.symbol);
    }

    let mut out = rustc_hash::FxHashSet::default();

    let mark_if_conflict = |out: &mut rustc_hash::FxHashSet<ExprRef>, e: ExprRef, label: &str| {
        if !state_symbols.contains(&e) {
            return;
        }
        let state_name = ctx[e].get_symbol_name(ctx).unwrap_or("");
        if state_name.is_empty() || is_autogen_name(state_name) {
            return;
        }
        if state_name != label {
            out.insert(e);
        }
    };

    for o in sys.outputs.iter() {
        mark_if_conflict(&mut out, o.expr, &ctx[o.name]);
    }
    for (i, &e) in sys.constraints.iter().enumerate() {
        let lbl = label_name(ctx, sys, e, "constraint", i);
        mark_if_conflict(&mut out, e, &lbl);
    }
    for (i, &e) in sys.bad_states.iter().enumerate() {
        let lbl = label_name(ctx, sys, e, "bad", i);
        mark_if_conflict(&mut out, e, &lbl);
    }

    out
}

fn collect_label_names(
    ctx: &Context,
    sys: &TransitionSystem,
) -> rustc_hash::FxHashSet<String> {
    let mut out = rustc_hash::FxHashSet::default();
    for out_sig in sys.outputs.iter() {
        out.insert(ctx[out_sig.name].clone());
    }
    for (i, &e) in sys.constraints.iter().enumerate() {
        out.insert(label_name(ctx, sys, e, "constraint", i));
    }
    for (i, &e) in sys.bad_states.iter().enumerate() {
        out.insert(label_name(ctx, sys, e, "bad", i));
    }
    out
}

fn label_name(
    ctx: &Context,
    sys: &TransitionSystem,
    e: ExprRef,
    default: &str,
    i: usize,
) -> String {
    ctx[e]
        .get_symbol_name(ctx)
        .map(|s| s.to_string())
        .or_else(|| sys.names[e].map(|s| ctx[s].clone()))
        .unwrap_or_else(|| format!("{default}{i}"))
}

fn write_node<W: Write>(
    writer: &mut W,
    ctx: &Context,
    id: u64,
    sort: u64,
    expr: &Expr,
    children: &[u64],
) -> std::io::Result<()> {
    match expr {
        Expr::BVSymbol { .. } | Expr::ArraySymbol { .. } => unreachable!(
            "symbols are handled by the caller and never emitted as regular nodes"
        ),

        Expr::BVLiteral(value) => write_bv_literal(writer, ctx, id, sort, *value),

        Expr::BVZeroExt { by, .. } => writeln!(writer, "{id} uext {sort} {} {by}", children[0]),
        Expr::BVSignExt { by, .. } => writeln!(writer, "{id} sext {sort} {} {by}", children[0]),
        Expr::BVSlice { hi, lo, .. } => {
            writeln!(writer, "{id} slice {sort} {} {hi} {lo}", children[0])
        }

        Expr::BVNot(_, _) => writeln!(writer, "{id} not {sort} {}", children[0]),
        Expr::BVNegate(_, _) => writeln!(writer, "{id} neg {sort} {}", children[0]),

        Expr::BVEqual(_, _) | Expr::ArrayEqual(_, _) => {
            writeln!(writer, "{id} eq {sort} {} {}", children[0], children[1])
        }
        Expr::BVImplies(_, _) => {
            writeln!(writer, "{id} implies {sort} {} {}", children[0], children[1])
        }
        Expr::BVGreater(_, _) => {
            writeln!(writer, "{id} ugt {sort} {} {}", children[0], children[1])
        }
        Expr::BVGreaterSigned(_, _, _) => {
            writeln!(writer, "{id} sgt {sort} {} {}", children[0], children[1])
        }
        Expr::BVGreaterEqual(_, _) => {
            writeln!(writer, "{id} ugte {sort} {} {}", children[0], children[1])
        }
        Expr::BVGreaterEqualSigned(_, _, _) => {
            writeln!(writer, "{id} sgte {sort} {} {}", children[0], children[1])
        }
        Expr::BVConcat(_, _, _) => {
            writeln!(writer, "{id} concat {sort} {} {}", children[0], children[1])
        }

        Expr::BVAnd(_, _, _) => writeln!(writer, "{id} and {sort} {} {}", children[0], children[1]),
        Expr::BVOr(_, _, _) => writeln!(writer, "{id} or {sort} {} {}", children[0], children[1]),
        Expr::BVXor(_, _, _) => writeln!(writer, "{id} xor {sort} {} {}", children[0], children[1]),
        Expr::BVShiftLeft(_, _, _) => {
            writeln!(writer, "{id} sll {sort} {} {}", children[0], children[1])
        }
        Expr::BVArithmeticShiftRight(_, _, _) => {
            writeln!(writer, "{id} sra {sort} {} {}", children[0], children[1])
        }
        Expr::BVShiftRight(_, _, _) => {
            writeln!(writer, "{id} srl {sort} {} {}", children[0], children[1])
        }
        Expr::BVAdd(_, _, _) => writeln!(writer, "{id} add {sort} {} {}", children[0], children[1]),
        Expr::BVMul(_, _, _) => writeln!(writer, "{id} mul {sort} {} {}", children[0], children[1]),
        Expr::BVSignedDiv(_, _, _) => {
            writeln!(writer, "{id} sdiv {sort} {} {}", children[0], children[1])
        }
        Expr::BVUnsignedDiv(_, _, _) => {
            writeln!(writer, "{id} udiv {sort} {} {}", children[0], children[1])
        }
        Expr::BVSignedMod(_, _, _) => {
            writeln!(writer, "{id} smod {sort} {} {}", children[0], children[1])
        }
        Expr::BVSignedRem(_, _, _) => {
            writeln!(writer, "{id} srem {sort} {} {}", children[0], children[1])
        }
        Expr::BVUnsignedRem(_, _, _) => {
            writeln!(writer, "{id} urem {sort} {} {}", children[0], children[1])
        }
        Expr::BVSub(_, _, _) => writeln!(writer, "{id} sub {sort} {} {}", children[0], children[1]),

        Expr::BVArrayRead { .. } => {
            writeln!(writer, "{id} read {sort} {} {}", children[0], children[1])
        }

        Expr::BVIte { .. } | Expr::ArrayIte { .. } => writeln!(
            writer,
            "{id} ite {sort} {} {} {}",
            children[0], children[1], children[2]
        ),

        Expr::ArrayStore { .. } => writeln!(
            writer,
            "{id} write {sort} {} {} {}",
            children[0], children[1], children[2]
        ),

        Expr::ArrayConstant { .. } => Err(std::io::Error::new(
            std::io::ErrorKind::InvalidData,
            "cannot serialize ArrayConstant outside of a state's init position: \
             core BTOR2 has no operator for constant arrays",
        )),
    }
}

fn write_bv_literal<W: Write>(
    writer: &mut W,
    ctx: &Context,
    id: u64,
    sort: u64,
    value: BVLitValue,
) -> std::io::Result<()> {
    let v = value.get(ctx);
    let width = value.width();
    if v.is_zero() {
        writeln!(writer, "{id} zero {sort}")
    } else if width > 1 && v.is_all_ones() {
        writeln!(writer, "{id} ones {sort}")
    } else if is_bv_one(&v) {
        // width == 1 and v == 1 is also `ones`, but `one` reads just as well and keeps
        // round-trips stable (parser accepts either).
        writeln!(writer, "{id} one {sort}")
    } else {
        writeln!(writer, "{id} const {sort} {}", v.to_bit_str())
    }
}

fn is_bv_one<V: BitVecOps>(v: &V) -> bool {
    if v.width() == 0 {
        return false;
    }
    let one = baa::BitVecValue::from_u64(1, v.width());
    v.is_equal(&one)
}
