(set-option :incremental true)
(set-option :produce-models true)
(set-logic QF_ABV)
(declare-const reg0@1 Bool)
(declare-const reg1@1 Bool)
(declare-const clk@1 Bool)
(define-fun |Delay.sv:14.9-14.53@1| () Bool (and  true (not  (not  (and  (not  reg0@1) reg1@1)))))
(define-fun reg0@2 () Bool true)
(define-fun reg1@2 () Bool reg0@1)
(declare-const clk@2 Bool)
(define-fun |Delay.sv:14.9-14.53@2| () Bool (and  true (not  (not  (and  (not  reg0@2) reg1@2)))))
(check-sat-assuming ((and  (and  true (=  reg0@1 false)) (=  reg1@1 false)) (or  false (and  true (not  (not  (and  (not  reg0@1) reg1@1))))) ))
(check-sat-assuming (true (or  false (and  true (not  (not  (and  (not  reg0@1) reg1@1))))) ))
(get-value (reg0@1))
(get-value (reg1@1))
(get-value (reg0@1))
(get-value (reg1@1))
(get-value (clk@1))
(check-sat-assuming ((and  (and  true (=  reg0@1 false)) (=  reg1@1 false)) (and  (and  true (=  reg0@2 false)) (=  reg1@2 true)) (or  (or  false (not  (=  reg0@1 false))) (not  (=  reg1@1 true))) ))
(check-sat-assuming ((and  (and  true (=  reg0@1 false)) (=  reg1@1 false)) (and  true (=  reg1@1 true)) ))
(check-sat-assuming ((and  (and  true (=  reg0@1 false)) (=  reg1@1 false)) (and  true (=  reg1@2 true)) ))
(check-sat-assuming ((and  true (or  false (not  (=  reg1@1 true)))) (or  false (and  true (not  (not  (and  (not  reg0@1) reg1@1))))) ))
(check-sat-assuming ((and  true (or  false (not  (=  reg1@1 true)))) (and  true (=  reg1@2 true)) ))
(check-sat-assuming (true (or  false (and  true (not  (not  (and  (not  reg0@1) reg1@1))))) ))
(get-value (reg0@1))
(get-value (reg1@1))
(get-value (reg0@1))
(get-value (reg1@1))
(get-value (clk@1))
(check-sat-assuming ((and  true (or  false (not  (=  reg1@1 true)))) (and  (and  true (=  reg0@2 false)) (=  reg1@2 true)) (or  (or  false (not  (=  reg0@1 false))) (not  (=  reg1@1 true))) ))
(check-sat-assuming ((and  (and  true (=  reg0@1 false)) (=  reg1@1 false)) (and  true (=  reg1@1 true)) ))
(check-sat-assuming ((and  true (or  false (not  (=  reg1@1 true)))) (and  true (=  reg1@2 true)) ))
(check-sat-assuming ((and  (and  true (=  reg0@1 false)) (=  reg1@1 false)) (and  true (=  reg0@1 false)) ))
(check-sat-assuming ((and  true (or  (or  false (not  (=  reg0@1 false))) (not  (=  reg1@1 true)))) (or  false (and  true (not  (not  (and  (not  reg0@1) reg1@1))))) ))
(check-sat-assuming ((and  (and  true (or  false (not  (=  reg1@1 true)))) (or  (or  false (not  (=  reg0@1 false))) (not  (=  reg1@1 true)))) (and  true (=  reg1@2 true)) ))
(check-sat-assuming ((and  (and  true (or  false (not  (=  reg1@1 true)))) (or  (or  false (not  (=  reg0@1 false))) (not  (=  reg1@1 true)))) (and  (and  true (=  reg0@2 false)) (=  reg1@2 true)) ))
(check-sat-assuming ((and  (and  true (or  (or  false (not  (=  reg0@1 false))) (not  (=  reg1@1 true)))) (or  (or  false (not  (=  reg0@1 false))) (not  (=  reg1@1 true)))) (and  (and  true (=  reg0@2 false)) (=  reg1@2 true)) ))
(check-sat-assuming ((and  (and  true (or  (or  false (not  (=  reg0@1 false))) (not  (=  reg1@1 true)))) (or  (or  false (not  (=  reg0@1 false))) (not  (=  reg1@1 true)))) (and  (and  true (=  reg0@2 false)) (=  reg1@2 true)) ))
(exit)
