(set-option :incremental true)
(set-option :produce-models true)
(set-logic QF_ABV)
(declare-const count@1 (_ BitVec 2))
(declare-const clk@1 Bool)
(define-fun |Overflow.sv:9.9-9.31@1| () Bool (and  true (not  (not  (=  count@1 #b00)))))
(define-fun count@2 () (_ BitVec 2) (bvadd  count@1 (ite  true #b01 #b00)))
(declare-const clk@2 Bool)
(define-fun |Overflow.sv:9.9-9.31@2| () Bool (and  true (not  (not  (=  count@2 #b00)))))
(check-sat-assuming ((and  true (=  count@1 #b10)) (or  false (and  true (not  (not  (=  count@1 #b00))))) ))
(check-sat-assuming (true (or  false (and  true (not  (not  (=  count@1 #b00))))) ))
(get-value (count@1))
(get-value (count@1))
(get-value (clk@1))
(check-sat-assuming ((and  true (=  count@1 #b10)) (and  (and  true (=  (= ((_ extract 0 0)  count@2) #b1) false)) (=  (= ((_ extract 1 1)  count@2) #b1) false)) (or  (or  false (not  (=  (= ((_ extract 0 0)  count@1) #b1) false))) (not  (=  (= ((_ extract 1 1)  count@1) #b1) false))) ))
(check-sat-assuming ((and  true (=  count@1 #b10)) (and  true (=  (= ((_ extract 1 1)  count@1) #b1) false)) ))
(check-sat-assuming ((and  true (=  count@1 #b10)) (and  true (=  (= ((_ extract 1 1)  count@2) #b1) false)) ))
(check-sat-assuming ((and  true (or  false (not  (=  (= ((_ extract 1 1)  count@1) #b1) false)))) (or  false (and  true (not  (not  (=  count@1 #b00))))) ))
(check-sat-assuming ((and  true (or  false (not  (=  (= ((_ extract 1 1)  count@1) #b1) false)))) (and  true (=  (= ((_ extract 1 1)  count@2) #b1) false)) ))
(check-sat-assuming (true (or  false (and  true (not  (not  (=  count@1 #b00))))) ))
(get-value (count@1))
(get-value (count@1))
(get-value (clk@1))
(check-sat-assuming ((and  true (or  false (not  (=  (= ((_ extract 1 1)  count@1) #b1) false)))) (and  (and  true (=  (= ((_ extract 0 0)  count@2) #b1) false)) (=  (= ((_ extract 1 1)  count@2) #b1) false)) (or  (or  false (not  (=  (= ((_ extract 0 0)  count@1) #b1) false))) (not  (=  (= ((_ extract 1 1)  count@1) #b1) false))) ))
(get-value (count@1))
(get-value (count@1))
(get-value (clk@1))
(check-sat-assuming ((and  true (=  count@1 #b10)) (and  (and  true (=  (= ((_ extract 0 0)  count@2) #b1) true)) (=  (= ((_ extract 1 1)  count@2) #b1) true)) (or  (or  false (not  (=  (= ((_ extract 0 0)  count@1) #b1) true))) (not  (=  (= ((_ extract 1 1)  count@1) #b1) true))) ))
(get-value (count@1))
(get-value (count@1))
(get-value (clk@1))
(exit)
