(set-option :incremental true)
(set-option :produce-models true)
(set-logic QF_ABV)
(declare-const a@1 Bool)
(declare-const b@1 Bool)
(declare-const clk@1 Bool)
(define-fun |Swap.sv:13.9-13.24@1| () Bool (and  true (not  (not  (=  a@1 b@1)))))
(define-fun a@2 () Bool b@1)
(define-fun b@2 () Bool a@1)
(declare-const clk@2 Bool)
(define-fun |Swap.sv:13.9-13.24@2| () Bool (and  true (not  (not  (=  a@2 b@2)))))
(check-sat-assuming ((and  (and  true (=  a@1 false)) (=  b@1 true)) (or  false (and  true (not  (not  (=  a@1 b@1))))) ))
(check-sat-assuming (true (or  false (and  true (not  (not  (=  a@1 b@1))))) ))
(get-value (a@1))
(get-value (b@1))
(get-value (a@1))
(get-value (b@1))
(get-value (clk@1))
(check-sat-assuming ((and  (and  true (=  a@1 false)) (=  b@1 true)) (and  (and  true (=  a@2 false)) (=  b@2 false)) (or  (or  false (not  (=  a@1 false))) (not  (=  b@1 false))) ))
(check-sat-assuming ((and  (and  true (=  a@1 false)) (=  b@1 true)) (and  true (=  b@1 false)) ))
(check-sat-assuming ((and  (and  true (=  a@1 false)) (=  b@1 true)) (and  true (=  b@2 false)) ))
(check-sat-assuming ((and  (and  true (=  a@1 false)) (=  b@1 true)) (and  true (=  a@1 false)) ))
(check-sat-assuming ((and  true (or  (or  false (not  (=  a@1 false))) (not  (=  b@1 false)))) (or  false (and  true (not  (not  (=  a@1 b@1))))) ))
(get-value (a@1))
(get-value (b@1))
(get-value (a@1))
(get-value (b@1))
(get-value (clk@1))
(check-sat-assuming ((and  (and  true (=  a@1 false)) (=  b@1 true)) (and  (and  true (=  a@2 true)) (=  b@2 true)) (or  (or  false (not  (=  a@1 true))) (not  (=  b@1 true))) ))
(check-sat-assuming ((and  (and  true (=  a@1 false)) (=  b@1 true)) (and  true (=  b@1 true)) ))
(check-sat-assuming ((and  (and  true (=  a@1 false)) (=  b@1 true)) (and  true (=  a@1 true)) ))
(check-sat-assuming ((and  (and  true (=  a@1 false)) (=  b@1 true)) (and  true (=  a@2 true)) ))
(check-sat-assuming ((and  (and  true (or  (or  false (not  (=  a@1 false))) (not  (=  b@1 false)))) (or  (or  false (not  (=  a@1 true))) (not  (=  b@1 true)))) (or  false (and  true (not  (not  (=  a@1 b@1))))) ))
(check-sat-assuming ((and  (and  true (or  (or  false (not  (=  a@1 false))) (not  (=  b@1 false)))) (or  (or  false (not  (=  a@1 true))) (not  (=  b@1 true)))) (and  (and  true (=  a@2 false)) (=  b@2 false)) ))
(check-sat-assuming ((and  (and  true (or  (or  false (not  (=  a@1 false))) (not  (=  b@1 false)))) (or  (or  false (not  (=  a@1 true))) (not  (=  b@1 true)))) (and  (and  true (=  a@2 true)) (=  b@2 true)) ))
(exit)
