(set-option :incremental true)
(set-option :produce-models true)
(set-logic QF_ABV)
(declare-const _bad_0@1 Bool)
(declare-const trigger@1 Bool)
(define-fun _bad_0@2 () Bool trigger@1)
(declare-const trigger@2 Bool)
(check-sat-assuming ((and  true (=  _bad_0@1 false)) (or  false _bad_0@1) ))
(check-sat-assuming (true (or  false _bad_0@1) ))
(get-value (_bad_0@1))
(get-value (_bad_0@1))
(get-value (trigger@1))
(check-sat-assuming ((and  true (=  _bad_0@1 false)) (and  true (=  _bad_0@2 true)) (or  false (not  (=  _bad_0@1 true))) ))
(get-value (_bad_0@1))
(get-value (_bad_0@1))
(get-value (trigger@1))
(exit)
