(set-option :incremental true)
(set-option :produce-models true)
(set-logic QF_ABV)
(declare-const _bad_0@1 Bool)
(define-fun _bad_0@2 () Bool true)
(check-sat-assuming ((and  true (=  _bad_0@1 true)) (or  false _bad_0@1) ))
(get-value (_bad_0@1))
(get-value (_bad_0@1))
(exit)
